### ISSUE TITLE
License the repository

### ISSUE THREAD

**Issue by tushar5526** [digilocker-tools/ts-sdk#6]
## Description
Add a relevant license to all the public repositories

## Goals
- [ ] Discussion on which license to use

## Expected Outcome
A license is added to each public repo

## Acceptance Criteria
- [ ] A license is added to each public repo\

## Implementation Details
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

## Mockups / Wireframes
NA

---

### Project
TS-sdk

### Organization Name:
Samagra

### Domain
Social Welfare

### Tech Skills Needed:
NA

### Mentor(s)
@tushar5526 @ChakshuGautam 

### Complexity
Low

### Category
Feature

### Sub Category
License

**Comment by masterismail** [comment]
hey ! are these the repos that you are talking about, [repos](https://github.com/orgs/digilocker-tools/repositories)
if yes, then only 2 of them contain the code. Shall I add the license to both?

**Comment by inkerton** [comment]
I would like to contribute to it. Please assign it to me.

**Comment by tushar5526** [comment]
Hi, thanks for the interest. We will be adding this internally.
